#!/usr/bin/with-contenv sh


consul-template -consul ${CONSUL_ADDRESS} -config /etc/consul-template/conf-cont.d -once

echo "==> Enabling services configuration"
rm -f /etc/services.d/consul-template/down
