#!/usr/bin/with-contenv sh

if [ -z ${CERT_EMAIL} ]; then
    echo "==> Not set varaible CERT_EMAIL"
    exit 1
fi
export CERT_EMAIL
printf "%s" "${CERT_EMAIL}" > /var/run/s6/container_environment/CERT_EMAIL

if [ -z ${CERT_DOMAIN} ]; then
    echo "==> Not set varaible CERT_DOMAIN"
    exit 1
fi
export CERT_DOMAIN
printf "%s" "${CERT_DOMAIN}" > /var/run/s6/container_environment/CERT_DOMAIN

if [ ! -d "/data/letsencrypt/live/" ]; then
  FLAGS=""
  if [ -z ${CERT_PRODACTION} ]; then
    echo "==> CERT_PRODACTION=false, use --test-cert"
    FLAGS="--test-cert"
  fi
  certbot certonly ${FLAGS} --standalone --config /etc/cli.ini --email ${CERT_EMAIL} -d ${CERT_DOMAIN}
fi

sed -i -e "s/example.com/${CERT_DOMAIN}/g" /etc/nginx/nginx.conf

SERVICE_CRON=1
export SERVICE_CRON
printf "%s" "${SERVICE_CRON}" > /var/run/s6/container_environment/SERVICE_CRON
