#!/usr/bin/with-contenv sh

if [ -d /etc/cont-consul/services.d/ ]; then
    for file in /etc/cont-consul/services.d/*.json; do
        [ -f $file ] || continue

        serviceid=`jq -r '.ID' $file`
        curl -sSL -X GET "http://${CONSUL_ADDRESS}/v1/agent/service/deregister/${serviceid}"
    done
fi

if [ -d /etc/cont-consul/checks.d/ ]; then
    for file in /etc/cont-consul/checks.d/*.json; do
        [ -f $file ] || continue

        checkid=`jq -r '.ID' $file`
        curl -sSL -X GET "http://${CONSUL_ADDRESS}/v1/agent/check/deregister/${checkid}"
    done
fi
