#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: reangd/postgresql
  tag: 14.1.0
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Moscow
  POSTGRESQL_TIMEZONE: Europe/Moscow
  POSTGRESQL_LOG_TIMEZONE: Europe/Moscow

secret:
  POSTGRESQL_PASSWORD: "password123"
  POSTGRESQL_ARCHIVE_TIMEOUT: 600
  WALG_COMPRESSION_METHOD: "brotli"
  WALG_BACKUP_TIME: "0 6 * * *"
  WALG_DELTA_MAX_STEPS: 6
  WALG_BACKUP_DEL_RETAIN: 4

service:
  main:
    ports:
      http:
        enabled: false
      tcp-postgresql:
        enabled: true
        protocol: TCP
        port: 5432

persistence:
  psql_data:
    enabled: true
    mountPath: /bitnami/postgresql
  psql_backup:
    enabled: true
    mountPath: /backup
