#!/usr/bin/with-contenv sh

CONTAINER_HOST=$(cat /etc/hostname)
if [ -z ${CONTAINER_HOST} ]; then
    echo "==> Not found CONTAINER_HOST"
    exit 1
fi
export CONTAINER_HOST
printf "%s" "${CONTAINER_HOST}" > /var/run/s6/container_environment/CONTAINER_HOST

CONTAINER_IP=$(ip route get 1|awk '{ print $NF; exit; }')
if [ -z ${CONTAINER_IP} ]; then
    echo "==> Not found CONTAINER_IP"
    exit 1
fi
export CONTAINER_IP
printf "%s" "${CONTAINER_IP}" > /var/run/s6/container_environment/CONTAINER_IP

CONTAINER_GATEWAY=$(ip route get 1|awk '{ print $3; exit; }')
if [ -z ${CONTAINER_GATEWAY} ]; then
    echo "==> Not found CONTAINER_GATEWAY"
    exit 1
fi
export CONTAINER_GATEWAY
printf "%s" "${CONTAINER_GATEWAY}" > /var/run/s6/container_environment/CONTAINER_GATEWAY

if [ ! -z ${CONTAINER_BACKUP} ]; then
	echo "==> Enabling backup"
	rm -f /etc/services.d/cron/down
fi
export CONTAINER_BACKUP
printf "%s" "${CONTAINER_BACKUP}" > /var/run/s6/container_environment/CONTAINER_BACKUP
