#!/usr/bin/with-contenv sh

if [ -z ${SERVICE_CRON} ]; then
    echo "==> Enabled cron service"
    rm -f /etc/services.d/cron/down
fi

export SERVICE_CRON
printf "%s" "${SERVICE_CRON}" > /var/run/s6/container_environment/SERVICE_CRON
