#!/usr/bin/with-contenv sh

add_dir () {
  if [ ! -d "/data/$2" ]; then
    mkdir /data/$2
  fi

  if [ ! -d "/data/$1" ]; then
    cp -rp /backup/$1 /data/$2
    chown -R nobody:www-data /dokuwiki/$1
  fi
}

add_dir "data" ""
add_dir "conf" ""
add_dir "lib/plugins" "lib/"
add_dir "lib/tpl" "lib/"
