name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  docker-image-release:
    runs-on: ubuntu-latest
    env:
      CONTEXT_SUBDIR: docker/postgresql/
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:${{ env.CONTEXT_SUBDIR }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgresql:14.1.0
